volumes:
  database_data:
    driver: local
  static_content:
    driver: local
networks:
  default:
    driver: bridge
services:
  geoparquet-backend:
    image: jjrom/geoparquet-backend:latest
    restart: always
    build:
      context: ./
      dockerfile: ./edito.Dockerfile
    environment:
      - GEOPARQUET_FILE=/data/skj_Badult_IPSL_F0.parquet
    ports:
      - 3001:3001
    volumes:
      - ./server.js:/usr/src/app/server.js
      - ./data:/data
      - ./cache:/cache